services:
  - type: web
    name: healthmate-ai
    env: python
    plan: free
    region: oregon
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: healthmate-ai.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: healthmate-db
          property: connectionString

databases:
  - name: healthmate-db
    plan: free
    region: oregon
