# Generated by Django 5.2.3 on 2025-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('steps', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
